import Providers from '@/providers';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Toast from '@/utils/toast';
import "./globals.css"
const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'GoPharma',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={roboto.className}>
            <body style={{ margin: 0 }}>
                <AntdRegistry>
                    <Toast />
                    <Providers>{children}</Providers>
                </AntdRegistry>
            </body>
        </html>
    );
}
